services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fastsearch_app
    volumes:
      - ./api:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - fastsearch_net

  nginx:
    image: nginx:stable-alpine
    container_name: fastsearch_nginx
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fastsearch_net

  mysql:
    image: mysql:8.0
    container_name: fastsearch_mysql
    restart: always
    environment:
      MYSQL_DATABASE: fastsearch
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fastsearch
      MYSQL_PASSWORD: fastsearch
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastsearch_net

  redis:
    image: redis/redis-stack:latest
    container_name: fastsearch_redis
    ports:
      - "6379:6379"   # Redis
      - "8001:8001"   # RedisInsight UI
    networks:
      - fastsearch_net

networks:
  fastsearch_net:

volumes:
  mysql_data: